package javagurus.curso.frameworks.model;
// default package
// Generated 1/12/2012 04:06:04 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipocuenta generated by hbm2java
 */
public class Tipocuenta implements java.io.Serializable {

	private BigDecimal idtipocuenta;
	private String nombre;	

	public Tipocuenta() {
	}

	public Tipocuenta(BigDecimal idtipocuenta, String nombre) {
		this.idtipocuenta = idtipocuenta;
		this.nombre = nombre;
	}

	public BigDecimal getIdtipocuenta() {
		return this.idtipocuenta;
	}

	public void setIdtipocuenta(BigDecimal idtipocuenta) {
		this.idtipocuenta = idtipocuenta;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
